### ISSUE TITLE
Condition((VSM_Map(vd, &ifantom)) == 0) not true

### ISSUE THREAD

**Issue by fgsch** [varnishcache/varnish-cache#2411]
Running `make check` on master from time to time I get:

```
...
**   top  13.0 === varnish v2 -vsc *poo*
**** v2   13.0 VSC MAIN.pools 1
**** v2   13.0 VSC LCK.mempool.creat 5
**** v2   13.0 VSC LCK.mempool.destroy 0
**** v2   13.0 VSC LCK.mempool.locks 73
**** v2   13.0 VSC MEMPOOL.busyobj.pool 10
**** v2   13.0 VSC MEMPOOL.req0.pool 10
*    diag  0.0 Assert error in VSC_Iter(), vsc.c line 348:
*    diag  0.0   Condition((VSM_Map(vd, &ifantom)) == 0) not true.
#    top  TEST ./tests/c00080.vtc FAILED (13.109) signal=6
```

**Comment by bsdphk** [comment]
I belive this is fixed in 515f93e03e9ee4bc08055424805efc4026bea0cb

**Comment by fgsch** [comment]
Looks like is still happening in the OSX job: https://travis-ci.org/varnishcache/varnish-cache/jobs/272795536

```
...
**   top   6.1 === varnish v1 -vsc *thr*
**** v1    6.1 VSC MAIN.fetch_no_thread 0
**** v1    6.1 VSC MAIN.threads 10
**** v1    6.1 VSC MAIN.threads_limited 0
**** v1    6.1 VSC MAIN.threads_created 21
**** v1    6.1 VSC MAIN.threads_destroyed 11
**** v1    6.1 VSC MAIN.threads_failed 0
**** v1    6.1 VSC MAIN.thread_queue_len 0
*    diag  0.0 Assert error in VSC_Iter(), vsc.c line 361:
*    diag  0.0   Condition((VSM_Map(vsc->vsm, &ifantom)) == 0) not true.
#    top  TEST ./tests/c00080.vtc FAILED (6.068) signal=6
FAIL tests/c00080.vtc (exit status: 2)
```

**Comment by bsdphk** [comment]
I have not been able to reproduce this on FreeBSD with 4c4759af148, despite hammering c00080 very hard.
