### ISSUE TITLE
Assert error in VBP_Control()

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#3362]
```
$ varnishadm panic.show
Panic at: Wed, 08 Jul 2020 13:32:10 GMT
Assert error in VBP_Control(), cache/cache_backend_probe.c line 661:
  Condition(vt->heap_idx != BINHEAP_NOIDX) not true.
version = varnish-trunk revision 5f3df940644fbef4547005b98c4f059df6c4ed79, vrt api = 11.0
ident = Linux,3.10.0-862.14.4.el7.x86_64,x86_64,-jnone,-smalloc,-sdefault,-hcritbit,epoll
now = 51407961.129085 (mono), 1594214925.481400 (real)
Backtrace:
  0x4467ca: /opt/varnish/sbin/varnishd() [0x4467ca]
  0x446ddc: /opt/varnish/sbin/varnishd() [0x446ddc]
  0x4d173b: /opt/varnish/sbin/varnishd(VAS_Fail+0x53) [0x4d173b]
  0x41ce19: /opt/varnish/sbin/varnishd(VBP_Control+0x175) [0x41ce19]
  0x418ff9: /opt/varnish/sbin/varnishd() [0x418ff9]
  0x4253bb: /opt/varnish/sbin/varnishd(VDI_Event+0x94) [0x4253bb]
  0x4593bf: /opt/varnish/sbin/varnishd() [0x4593bf]
  0x459e60: /opt/varnish/sbin/varnishd() [0x459e60]
  0x45af4d: /opt/varnish/sbin/varnishd() [0x45af4d]
  0x4d2e7c: /opt/varnish/sbin/varnishd() [0x4d2e7c]
pthread.self = 0x7f24f08e2780
pthread.name = (cache-main)
```

code is https://github.com/nigoroll/varnish-cache/commit/5f3df940644fbef4547005b98c4f059df6c4ed79
based upon d33f4a86098ac93c141c97ebf4f710cab417052f

**Comment by bsdphk** [comment]
See also:

http://varnish-cache.org/vtest/attachment_50a59f1058017d540b0dccfb5bee18a36bf39923_Debian_x86_64_buster_sid_1.04_clang_uplex_v00003.txt

**Comment by bsdphk** [comment]
Note that the Vtest error above contains:

    **   s1   === rxreq
    **** dT   13.044
    **** s1   rxhdrlen = 0
    ---- s1   HTTP header is incomplete
    ***  v1   debug|Error: Child (32051) not responding to CLI, killed it.
    ***  v1   debug|Error: Please file ticket: VCL poker problem: 'vcl.state vcl2 0auto' -> 400 'CLI communication error (hdr)'
    ***  v1   debug|Error: Child (32051) died signal=6
    **** dT   13.048

**Comment by nigoroll** [comment]
bugwash: discussed hypothesis that we process a COLD event before vbp_task got to the mtx for the initial call.
Will check.

**Comment by darjisanket** [comment]
@nigoroll we are also facing similar problem with varnish cache 6 any fix available

**Comment by n4n0r** [comment]
Hi, 
I can confirm we are seeing the same panic with varnish 6.4.0.

```
Panic at: Fri, 30 Oct 2020 04:39:26 GMT
Assert error in VBP_Control(), cache/cache_backend_probe.c line 661:
  Condition(vt->heap_idx != BINHEAP_NOIDX) not true.
version = varnish-6.4.0 revision 13f137934ec1cf14af66baf7896311115ee35598, vrt api = 11.0
ident = Linux,4.4.0-164-generic,x86_64,-junix,-smalloc,-sdefault,-hcritbit,epoll
now = 35057694.336129 (mono), 1604032760.963739 (real)
Backtrace:
  0x43e01a: /usr/sbin/varnishd() [0x43e01a]
  0x4a5063: /usr/sbin/varnishd(VAS_Fail+0x43) [0x4a5063]
  0x41d2c8: /usr/sbin/varnishd(VBP_Control+0x158) [0x41d2c8]
  0x4194c2: /usr/sbin/varnishd() [0x4194c2]
  0x44c463: /usr/sbin/varnishd() [0x44c463]
  0x44d48d: /usr/sbin/varnishd() [0x44d48d]
  0x44ed6a: /usr/sbin/varnishd(VCL_Poll+0xaa) [0x44ed6a]
  0x422756: /usr/sbin/varnishd() [0x422756]
  0x4a70da: /usr/sbin/varnishd() [0x4a70da]
  0x4a77c4: /usr/sbin/varnishd(VCLS_Poll+0x374) [0x4a77c4]
thread = (cache-main)
pthread.attr = {
  guard = 0,
  stack_bottom = 0x7fffd1d4b000,
  stack_top = 0x7fffd254a000,
  stack_size = 8384512,
}
thr.req = (nil) {
},
thr.busyobj = (nil) {
},
vmods = {
  directors = {0x7fc07a508240, Varnish 6.4.0 13f137934ec1cf14af66baf7896311115ee35598, 0.0},
  geoip2 = {0x7fc07a5082b0, Varnish 6.4.0 13f137934ec1cf14af66baf7896311115ee35598, 0.0},
  std = {0x7fc07a508320, Varnish 6.4.0 13f137934ec1cf14af66baf7896311115ee35598, 0.0},
  blob = {0x7fc07a508f60, Varnish 6.4.0 13f137934ec1cf14af66baf7896311115ee35598, 0.0},
  cookie = {0x7fc07a508fd0, Varnish 6.4.0 13f137934ec1cf14af66baf7896311115ee35598, 0.0},
  header = {0x7fc07a5090b0, Varnish 6.4.0 13f137934ec1cf14af66baf7896311115ee35598, 11.0},
},

```

**Comment by Dridi** [comment]
Still a problem in trunk: https://varnish-cache.org/vtest/attachment_daf9b1979a3844f3a5be3841bb5342f3372748bc_FreeBSD_amd64_13.0-CUR_1.05_GCOV_phk_v00003.txt
